def get_topic_by_id(id):
    TOPICS_NUMBERING = {
        0: "Accidents with children",
        1: "Local authorities: appointments, resignations & statements",
        2: "*Urban development (misc)",
        3: "IT & military high tech",
        4: "Fires",
        5: "Urban demography & housing payments",
        6: "Police actions drug, alcohol & counterfeit money crimes",
        7: "Omsk region industrial developemnt",
        8: "Ads of banking services",
        9: "Holidays and VIP-weddingss",
        10: "Trials on economic crime",
        11: "Public transport and traffic",
        12: "Weather",
        13: "Yury Gamburg resignation",
        14: "*NATO warships in Black sea, Russian rocket launch & contests",
        15: "Regional parliament activities",
        16: "Urban landscaping & greening",
        17: "Schools, orphanages & child charity",
        18: "Car sales",
        19: "Car accidents",
        20: "Education",
        21: "Real estate: contruction",
        22: "Art and literature",
        23: "Street & bridge reconstruction & maintenance",
        24: "Housing & the case of disabled Akhmetov",
        25: "Stray dogs & doghunters",
        26: "Urban events & openings",
        27: "Crimea accession",
        28: "Concerts",
        29: "Sport, hockey",
        30: "Hockey",
        31: "Control & regulation of enterprises",
        32: "Regional taxes & fuel prices",
        33: "Missing persons announcements",
        34: "Theaters & festivals",
        35: "*Omsk media, plants & animals",
        36: "Local authorities: appointments, resignations & statements",
        37: "Macroeconomic events: currency rates & oil prices",
        38: "Housing: heating",
        39: "Russia, Ukraine & US international relations",
        40: "Beauty contests & their winners",
        41: "Arbitration court and the Mostovik case",
        42: "*Military holidays",
        43: "Criminal news",
        44: "Movies and Movie stars",
        45: "Olympic Games 2014 & Omsk athletes",
        46: "Uninterpretable",
        47: "Ivan Klimov’s murder",
        48: "Abridgments of traffic law",
        49: "Regional elections and misc."
    }
    return TOPICS_NUMBERING[id]